package com.mockapiproject.mockapi.Service.Impl;

import com.mockapiproject.mockapi.DTO.ColumnDTO;
import com.mockapiproject.mockapi.Entity.DatabaseConnectionEntity;
import com.mockapiproject.mockapi.Enum.DatabaseType;
import com.mockapiproject.mockapi.Service.TableManagementService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.sql.*;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class TableManagementServiceImpl implements TableManagementService {

    @Override
    public void createTable(DatabaseConnectionEntity connection, String tableName, List<ColumnDTO> columns) {
        if (columns == null || columns.isEmpty()) {
            throw new RuntimeException("At least one column is required");
        }

        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE \"").append(tableName).append("\" (");

        boolean first = true;
        for (ColumnDTO column : columns) {
            if (!first) {
                sql.append(", ");
            }
            first = false;

            sql.append("\"").append(column.getName()).append("\" ");
            sql.append(mapToDbType(column.getType(), connection.getDatabaseType()));

            if (column.getSize() != null && column.getSize() > 0) {
                if (column.getScale() != null && column.getScale() > 0) {
                    sql.append("(").append(column.getSize()).append(",").append(column.getScale()).append(")");
                } else {
                    sql.append("(").append(column.getSize()).append(")");
                }
            }

            if (Boolean.TRUE.equals(column.getIsPrimaryKey())) {
                sql.append(" PRIMARY KEY");
            }

            if (Boolean.TRUE.equals(column.getIsAutoIncrement())) {
                if (connection.getDatabaseType() == DatabaseType.POSTGRESQL) {
                    sql.append(" GENERATED BY DEFAULT AS IDENTITY");
                } else if (connection.getDatabaseType() == DatabaseType.MYSQL) {
                    sql.append(" AUTO_INCREMENT");
                }
            }

            if (Boolean.FALSE.equals(column.getIsNullable())) {
                sql.append(" NOT NULL");
            }

            if (column.getDefaultValue() != null && !column.getDefaultValue().isEmpty()) {
                sql.append(" DEFAULT ").append(column.getDefaultValue());
            }
        }

        sql.append(")");

        executeSql(connection, sql.toString());
    }

    @Override
    public void dropTable(DatabaseConnectionEntity connection, String tableName) {
        String sql = String.format("DROP TABLE IF EXISTS \"%s\"", tableName);
        executeSql(connection, sql);
    }

    @Override
    public void addColumn(DatabaseConnectionEntity connection, String tableName, ColumnDTO column) {
        StringBuilder sql = new StringBuilder();
        sql.append("ALTER TABLE \"").append(tableName).append("\" ADD COLUMN \"");
        sql.append(column.getName()).append("\" ");
        sql.append(mapToDbType(column.getType(), connection.getDatabaseType()));

        if (column.getSize() != null && column.getSize() > 0) {
            if (column.getScale() != null && column.getScale() > 0) {
                sql.append("(").append(column.getSize()).append(",").append(column.getScale()).append(")");
            } else {
                sql.append("(").append(column.getSize()).append(")");
            }
        }

        if (Boolean.FALSE.equals(column.getIsNullable())) {
            sql.append(" NOT NULL");
        }

        if (column.getDefaultValue() != null && !column.getDefaultValue().isEmpty()) {
            sql.append(" DEFAULT ").append(column.getDefaultValue());
        }

        executeSql(connection, sql.toString());
    }

    @Override
    public void dropColumn(DatabaseConnectionEntity connection, String tableName, String columnName) {
        String sql = String.format("ALTER TABLE \"%s\" DROP COLUMN \"%s\"", tableName, columnName);
        executeSql(connection, sql);
    }

    @Override
    public void insertRow(DatabaseConnectionEntity connection, String tableName, Map<String, Object> data) {
        if (data == null || data.isEmpty()) {
            throw new RuntimeException("Data is required");
        }

        StringBuilder columns = new StringBuilder();
        StringBuilder values = new StringBuilder();

        boolean first = true;
        for (Map.Entry<String, Object> entry : data.entrySet()) {
            if (!first) {
                columns.append(", ");
                values.append(", ");
            }
            first = false;

            columns.append("\"").append(entry.getKey()).append("\"");
            values.append("?");
        }

        String sql = String.format("INSERT INTO \"%s\" (%s) VALUES (%s)",
                tableName, columns.toString(), values.toString());

        executeSqlWithParams(connection, sql, data.values().toArray());
    }

    @Override
    public void updateRow(DatabaseConnectionEntity connection, String tableName, Object rowId,
            Map<String, Object> data) {
        if (data == null || data.isEmpty()) {
            throw new RuntimeException("Data is required");
        }

        // Get primary key column name
        String pkColumn = getPrimaryKeyColumn(connection, tableName);
        if (pkColumn == null) {
            throw new RuntimeException("Cannot update: table has no primary key");
        }

        StringBuilder setClause = new StringBuilder();
        boolean first = true;
        for (Map.Entry<String, Object> entry : data.entrySet()) {
            if (!first) {
                setClause.append(", ");
            }
            first = false;

            setClause.append("\"").append(entry.getKey()).append("\" = ?");
        }

        String sql = String.format("UPDATE \"%s\" SET %s WHERE \"%s\" = ?",
                tableName, setClause.toString(), pkColumn);

        // Add rowId as the last parameter
        Object[] params = new Object[data.size() + 1];
        int i = 0;
        for (Object value : data.values()) {
            params[i++] = value;
        }
        params[i] = rowId;

        executeSqlWithParams(connection, sql, params);
    }

    @Override
    public void deleteRow(DatabaseConnectionEntity connection, String tableName, Object rowId) {
        // Get primary key column name
        String pkColumn = getPrimaryKeyColumn(connection, tableName);
        if (pkColumn == null) {
            throw new RuntimeException("Cannot delete: table has no primary key");
        }

        String sql = String.format("DELETE FROM \"%s\" WHERE \"%s\" = ?", tableName, pkColumn);
        executeSqlWithParams(connection, sql, new Object[] { rowId });
    }

    private String getPrimaryKeyColumn(DatabaseConnectionEntity connection, String tableName) {
        String jdbcUrl = buildJdbcUrl(connection);

        try (java.sql.Connection conn = DriverManager.getConnection(
                jdbcUrl, connection.getUsername(), connection.getPassword())) {

            DatabaseMetaData metaData = conn.getMetaData();

            try (ResultSet rs = metaData.getPrimaryKeys(null, null, tableName)) {
                if (rs.next()) {
                    return rs.getString("COLUMN_NAME");
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Failed to get primary key: " + e.getMessage(), e);
        }

        return null;
    }

    private void executeSql(DatabaseConnectionEntity connection, String sql) {
        String jdbcUrl = buildJdbcUrl(connection);

        try (java.sql.Connection conn = DriverManager.getConnection(
                jdbcUrl, connection.getUsername(), connection.getPassword())) {

            try (Statement stmt = conn.createStatement()) {
                stmt.execute(sql);
            }

        } catch (SQLException e) {
            throw new RuntimeException("Failed to execute SQL: " + e.getMessage(), e);
        }
    }

    private void executeSqlWithParams(DatabaseConnectionEntity connection, String sql, Object[] params) {
        String jdbcUrl = buildJdbcUrl(connection);

        try (java.sql.Connection conn = DriverManager.getConnection(
                jdbcUrl, connection.getUsername(), connection.getPassword())) {

            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                for (int i = 0; i < params.length; i++) {
                    pstmt.setObject(i + 1, params[i]);
                }
                pstmt.execute();
            }

        } catch (SQLException e) {
            throw new RuntimeException("Failed to execute SQL: " + e.getMessage(), e);
        }
    }

    private String mapToDbType(String type, DatabaseType dbType) {
        if (type == null) {
            return "VARCHAR(255)";
        }

        // Normalize type name
        String normalizedType = type.toUpperCase();

        // Common type mappings
        switch (normalizedType) {
            case "STRING":
            case "VARCHAR":
                return "VARCHAR(255)";
            case "TEXT":
                return "TEXT";
            case "INT":
            case "INTEGER":
            case "NUMBER":
                return "INTEGER";
            case "LONG":
            case "BIGINT":
                return "BIGINT";
            case "DOUBLE":
            case "FLOAT":
            case "DECIMAL":
                return "DECIMAL(10,2)";
            case "BOOLEAN":
            case "BOOL":
                return dbType == DatabaseType.MYSQL ? "TINYINT(1)" : "BOOLEAN";
            case "DATE":
                return "DATE";
            case "TIME":
                return "TIME";
            case "TIMESTAMP":
            case "DATETIME":
                return "TIMESTAMP";
            case "UUID":
                return dbType == DatabaseType.POSTGRESQL ? "UUID" : "VARCHAR(36)";
            case "JSON":
                return dbType == DatabaseType.POSTGRESQL ? "JSONB" : "JSON";
            default:
                return "VARCHAR(255)";
        }
    }

    private String buildJdbcUrl(DatabaseConnectionEntity connection) {
        if (connection.getDatabaseType() == DatabaseType.POSTGRESQL) {
            return String.format("jdbc:postgresql://%s:%d/%s?sslmode=require",
                    connection.getHost(), connection.getPort(), connection.getDatabaseName());
        } else if (connection.getDatabaseType() == DatabaseType.MYSQL) {
            return String.format("jdbc:mysql://%s:%d/%s?useSSL=false&allowPublicKeyRetrieval=true",
                    connection.getHost(), connection.getPort(), connection.getDatabaseName());
        }
        throw new RuntimeException("Unsupported database type");
    }
}
